#pragma once

// DO NOT EDIT THIS FILE, IT GETS AUTOMATICALLY GENERATED AT BUILDTIME. ANY CHANGES WILL BE LOST

const char *frag_src = R"(#version 450 core

out vec4 FragColor;

in vec2 tex_coord;

uniform vec2 size;
uniform vec4 color;
uniform float radius;

void main() {
   FragColor = color;
})")